/* ============================================================
   BHS INGGRIS — KONFIGURASI DEFAULT (WHITE-LABEL)
   ------------------------------------------------------------
   Edit file ini untuk mengubah branding secara PERMANEN
   (berlaku untuk semua pengunjung setelah deploy).

   Cara paling mudah:
   1. Buka /admin.html lalu atur branding lewat panel admin.
   2. Di tab "Data", klik "Salin sebagai config.default.js".
   3. Tempel (replace) seluruh isi file ini, lalu deploy ulang.
   ============================================================ */

window.EFQ_DEFAULT_CONFIG = {
  brand: {
    appName: "Bhs Inggris",
    tagline: "Bermain sambil belajar Bahasa Inggris!",
    logoUrl: "",
    primaryColor: "#2EC4B6",
    accentColor: "#FF6B6B",
    starColor: "#F5A623",
    footerText: "English Fun Starter for Kids · by produkvip",
    showCredit: true
  },

  settings: {
    questionsPerRound: 8,
    adminPasswordHash: "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
    games: {
      warna: true,
      angka: true,
      kata: true,
      eja: true,
      dengar: true,
      dengararti: true,
      dengarkalimat: true,
      dengareja: true,
      ucap: true,
      ucapkalimat: true,
      kalimat: true,
      antonim: true,
      plural: true,
      kosong: true,
      tubuh: true,
      aksi: true,
      posisi: true,
      perasaan: true,
      cuaca: true,
      tanya: true,
      tobe: true,
      pronoun: true,
      article: true,
      possessive: true,
      present: true,
      hewan: true,
      buah: true,
      sayur: true,
      keluarga: true,
      sekolah: true,
      pakaian: true,
      transport: true,
      tempat: true,
      makanan: true,
      minuman: true,
      rumah: true,
      pekerjaan: true,
      hobi: true,
      waktu: true,
      kalender: true,
      mainan: true,
      olahraga: true,
      alam: true
    }
  },

  content: {
    vocab: [
      ["Cat", "Kucing"], ["Dog", "Anjing"], ["Fish", "Ikan"], ["Bird", "Burung"],
      ["Rabbit", "Kelinci"], ["Elephant", "Gajah"], ["Lion", "Singa"], ["Tiger", "Harimau"],
      ["Rice", "Nasi"], ["Bread", "Roti"], ["Egg", "Telur"], ["Milk", "Susu"],
      ["Apple", "Apel"], ["Banana", "Pisang"], ["Water", "Air"], ["Juice", "Jus"],
      ["Mother", "Ibu"], ["Father", "Ayah"], ["Sister", "Saudara perempuan"], ["Brother", "Saudara laki-laki"],
      ["Head", "Kepala"], ["Eyes", "Mata"], ["Nose", "Hidung"], ["Hands", "Tangan"],
      ["Book", "Buku"], ["Pencil", "Pensil"], ["Bag", "Tas"], ["Ball", "Bola"],
      ["Chair", "Kursi"], ["Table", "Meja"], ["House", "Rumah"], ["Door", "Pintu"],
      ["Happy", "Senang"], ["Sad", "Sedih"], ["Big", "Besar"], ["Small", "Kecil"],
      ["Sunny", "Cerah"], ["Rainy", "Hujan"], ["Shirt", "Kemeja"], ["Shoes", "Sepatu"],
      ["Teacher", "Guru"], ["Student", "Murid"], ["Classroom", "Ruang kelas"], ["Library", "Perpustakaan"],
      ["Kitchen", "Dapur"], ["Bedroom", "Kamar tidur"], ["Bathroom", "Kamar mandi"], ["Garden", "Taman"],
      ["Breakfast", "Sarapan"], ["Lunch", "Makan siang"], ["Dinner", "Makan malam"], ["Vegetable", "Sayuran"],
      ["Beautiful", "Cantik"], ["Difficult", "Sulit"], ["Important", "Penting"], ["Together", "Bersama"],
      ["Yesterday", "Kemarin"], ["Tomorrow", "Besok"], ["Careful", "Hati-hati"], ["Friendly", "Ramah"]
    ],
    spellWords: [
      ["CAT", "Kucing"], ["DOG", "Anjing"], ["RED", "Merah"], ["EGG", "Telur"],
      ["SUN", "Matahari"], ["HAT", "Topi"], ["BALL", "Bola"], ["BOOK", "Buku"],
      ["FISH", "Ikan"], ["MILK", "Susu"], ["STAR", "Bintang"], ["BLUE", "Biru"],
      ["HAND", "Tangan"], ["FIVE", "Lima"], ["GREEN", "Hijau"], ["SMILE", "Senyum"],
      ["CHAIR", "Kursi"], ["TABLE", "Meja"], ["SCHOOL", "Sekolah"], ["FRIEND", "Teman"],
      ["GARDEN", "Taman"], ["KITCHEN", "Dapur"], ["MORNING", "Pagi"], ["ANIMAL", "Hewan"],
      ["TEACHER", "Guru"], ["LIBRARY", "Perpustakaan"], ["RAINBOW", "Pelangi"], ["WINDOW", "Jendela"],
      ["PEN", "Pena"], ["CUP", "Cangkir"], ["BOX", "Kotak"], ["BUS", "Bus"],
      ["CAR", "Mobil"], ["BED", "Tempat tidur"], ["FROG", "Katak"], ["BIRD", "Burung"],
      ["TREE", "Pohon"], ["CAKE", "Kue"], ["MOON", "Bulan"], ["DOOR", "Pintu"],
      ["DUCK", "Bebek"], ["KITE", "Layang-layang"], ["APPLE", "Apel"], ["HAPPY", "Senang"],
      ["HOUSE", "Rumah"], ["FLOWER", "Bunga"], ["PENCIL", "Pensil"], ["ORANGE", "Jeruk"],
      ["BANANA", "Pisang"], ["ELEPHANT", "Gajah"], ["UMBRELLA", "Payung"], ["BIRTHDAY", "Ulang tahun"],
      ["COMPUTER", "Komputer"]
    ],
    listenWords: [
      "Cat", "Dog", "Fish", "Apple", "Banana", "Red", "Blue", "Book",
      "Star", "Hand", "Milk", "Egg", "Happy", "Rabbit", "Table", "Mother",
      "Teacher", "Student", "School", "Garden", "Kitchen", "Window", "Library", "Morning",
      "Breakfast", "Vegetable", "Beautiful", "Important", "Together", "Tomorrow"
    ],
    sentences: [
      ["I am happy", "Aku senang"],
      ["This is my book", "Ini bukuku"],
      ["I like apples", "Aku suka apel"],
      ["I have two pencils", "Aku punya dua pensil"],
      ["She is my mother", "Dia ibuku"],
      ["He is my father", "Dia ayahku"],
      ["The cat is small", "Kucing itu kecil"],
      ["I can swim", "Aku bisa berenang"],
      ["There is a cat", "Ada seekor kucing"],
      ["The ball is under the table", "Bola di bawah meja"],
      ["I wear a blue shirt", "Aku memakai kemeja biru"],
      ["I wake up in the morning", "Aku bangun di pagi hari"],
      ["We study English together", "Kami belajar Bahasa Inggris bersama"],
      ["My teacher is very kind", "Guruku sangat baik"],
      ["The students read books in the library", "Para murid membaca buku di perpustakaan"],
      ["I eat breakfast before school", "Aku sarapan sebelum sekolah"],
      ["Please close the window", "Tolong tutup jendela"],
      ["They are playing in the garden", "Mereka sedang bermain di taman"],
      ["My sister is wearing new shoes", "Saudara perempuanku memakai sepatu baru"],
      ["The weather is cloudy today", "Cuaca hari ini berawan"],
      ["I finished my homework yesterday", "Aku menyelesaikan PR-ku kemarin"],
      ["We will visit grandma tomorrow", "Kami akan mengunjungi nenek besok"],
      ["The children are drawing colorful animals", "Anak-anak sedang menggambar hewan berwarna-warni"],
      ["I see a bird", "Aku melihat seekor burung"],
      ["The dog is big", "Anjing itu besar"],
      ["We are good friends", "Kami teman baik"],
      ["The sun is very hot", "Matahari sangat panas"],
      ["She has a red bag", "Dia punya tas merah"],
      ["My brother likes to play football", "Kakakku suka bermain bola"],
      ["The little boy is playing with a ball", "Anak kecil itu bermain dengan bola"]
    ],
    opposites: [
      ["Big", "Small", "Besar - kecil"],
      ["Hot", "Cold", "Panas - dingin"],
      ["Happy", "Sad", "Senang - sedih"],
      ["Fast", "Slow", "Cepat - lambat"],
      ["Day", "Night", "Siang - malam"],
      ["Up", "Down", "Atas - bawah"],
      ["Open", "Closed", "Buka - tutup"],
      ["Clean", "Dirty", "Bersih - kotor"],
      ["Easy", "Difficult", "Mudah - sulit"],
      ["Early", "Late", "Awal - terlambat"],
      ["Beautiful", "Ugly", "Cantik - jelek"],
      ["Strong", "Weak", "Kuat - lemah"],
      ["Quiet", "Noisy", "Tenang - berisik"],
      ["Careful", "Careless", "Hati-hati - ceroboh"],
      ["Friendly", "Unfriendly", "Ramah - tidak ramah"],
      ["Tall", "Short", "Tinggi - pendek"],
      ["New", "Old", "Baru - lama"],
      ["Full", "Empty", "Penuh - kosong"],
      ["Rich", "Poor", "Kaya - miskin"],
      ["Left", "Right", "Kiri - kanan"],
      ["Wet", "Dry", "Basah - kering"],
      ["Hard", "Soft", "Keras - lembut"],
      ["Sweet", "Sour", "Manis - asam"],
      ["Young", "Old", "Muda - tua"],
      ["First", "Last", "Pertama - terakhir"],
      ["Bright", "Dark", "Terang - gelap"],
      ["Polite", "Rude", "Sopan - kasar"],
      ["Ancient", "Modern", "Kuno - modern"],
      ["Expensive", "Cheap", "Mahal - murah"],
      ["Wide", "Narrow", "Lebar - sempit"]
    ],
    plurals: [
      ["cat", "cats", "kucing"],
      ["dog", "dogs", "anjing"],
      ["book", "books", "buku"],
      ["apple", "apples", "apel"],
      ["chair", "chairs", "kursi"],
      ["box", "boxes", "kotak"],
      ["bus", "buses", "bus"],
      ["baby", "babies", "bayi"],
      ["city", "cities", "kota"],
      ["child", "children", "anak"],
      ["person", "people", "orang"],
      ["mouse", "mice", "tikus"],
      ["tooth", "teeth", "gigi"],
      ["leaf", "leaves", "daun"],
      ["knife", "knives", "pisau"],
      ["ball", "balls", "bola"],
      ["door", "doors", "pintu"],
      ["table", "tables", "meja"],
      ["house", "houses", "rumah"],
      ["bird", "birds", "burung"],
      ["foot", "feet", "kaki"],
      ["man", "men", "pria"],
      ["woman", "women", "wanita"],
      ["tomato", "tomatoes", "tomat"],
      ["potato", "potatoes", "kentang"],
      ["boy", "boys", "anak laki-laki"],
      ["girl", "girls", "anak perempuan"],
      ["watch", "watches", "jam tangan"],
      ["wolf", "wolves", "serigala"],
      ["sheep", "sheep", "domba"]
    ],
    fillBlanks: [
      ["I ____ a cat", "have", "Aku punya seekor kucing"],
      ["She ____ my sister", "is", "Dia saudara perempuanku"],
      ["We ____ English", "study", "Kami belajar Bahasa Inggris"],
      ["The bird can ____", "fly", "Burung itu bisa terbang"],
      ["I drink ____ every day", "water", "Aku minum air setiap hari"],
      ["He ____ a blue shirt", "wears", "Dia memakai kemeja biru"],
      ["They ____ in the garden", "play", "Mereka bermain di taman"],
      ["My mother cooks in the ____", "kitchen", "Ibuku memasak di dapur"],
      ["The students read in the ____", "library", "Para murid membaca di perpustakaan"],
      ["We eat breakfast before ____", "school", "Kami sarapan sebelum sekolah"],
      ["Please ____ the door slowly", "close", "Tolong tutup pintu perlahan"],
      ["I finished my homework ____", "yesterday", "Aku menyelesaikan PR-ku kemarin"],
      ["We will visit grandma ____", "tomorrow", "Kami akan mengunjungi nenek besok"],
      ["The children are drawing ____ animals", "colorful", "Anak-anak menggambar hewan berwarna-warni"],
      ["My teacher explains the lesson ____", "carefully", "Guruku menjelaskan pelajaran dengan hati-hati"],
      ["The sun is very ____", "hot", "Matahari sangat panas"],
      ["I ____ to school every day", "go", "Aku pergi ke sekolah setiap hari"],
      ["A dog can ____ loudly", "bark", "Anjing bisa menggonggong keras"],
      ["We sleep at ____", "night", "Kami tidur di malam hari"],
      ["She ____ a beautiful song", "sings", "Dia menyanyikan lagu yang indah"],
      ["Birds have two ____", "wings", "Burung punya dua sayap"],
      ["I brush my ____ every morning", "teeth", "Aku menyikat gigi setiap pagi"],
      ["The apple is ____ and sweet", "red", "Apel itu merah dan manis"],
      ["My father ____ a car", "drives", "Ayahku mengemudikan mobil"],
      ["We wear shoes on our ____", "feet", "Kami memakai sepatu di kaki"],
      ["The baby is ____ because it is hungry", "crying", "Bayi itu menangis karena lapar"],
      ["Please ____ your hands before eating", "wash", "Tolong cuci tanganmu sebelum makan"],
      ["I ____ my homework after dinner", "do", "Aku mengerjakan PR setelah makan malam"],
      ["The rain falls from the ____", "sky", "Hujan turun dari langit"],
      ["An elephant is very ____", "big", "Gajah sangat besar"]
    ],
    bodyParts: [
      ["Head", "Kepala"], ["Hair", "Rambut"], ["Eyes", "Mata"], ["Ears", "Telinga"],
      ["Nose", "Hidung"], ["Mouth", "Mulut"], ["Teeth", "Gigi"], ["Tongue", "Lidah"],
      ["Neck", "Leher"], ["Shoulder", "Bahu"], ["Arm", "Lengan"], ["Hand", "Tangan"],
      ["Finger", "Jari"], ["Chest", "Dada"], ["Stomach", "Perut"], ["Back", "Punggung"],
      ["Leg", "Kaki"], ["Knee", "Lutut"], ["Foot", "Telapak kaki"], ["Toe", "Jari kaki"],
      ["Face", "Wajah"], ["Cheek", "Pipi"], ["Chin", "Dagu"], ["Lips", "Bibir"],
      ["Elbow", "Siku"], ["Thumb", "Ibu jari"], ["Nail", "Kuku"], ["Ankle", "Pergelangan kaki"],
      ["Heart", "Jantung"], ["Brain", "Otak"]
    ],
    actions: [
      ["Run", "Berlari"], ["Walk", "Berjalan"], ["Jump", "Melompat"], ["Swim", "Berenang"],
      ["Read", "Membaca"], ["Write", "Menulis"], ["Draw", "Menggambar"], ["Sing", "Bernyanyi"],
      ["Dance", "Menari"], ["Eat", "Makan"], ["Drink", "Minum"], ["Sleep", "Tidur"],
      ["Open", "Membuka"], ["Close", "Menutup"], ["Listen", "Mendengarkan"], ["Speak", "Berbicara"],
      ["Climb", "Memanjat"], ["Laugh", "Tertawa"], ["Clean", "Membersihkan"], ["Study", "Belajar"],
      ["Fly", "Terbang"], ["Sit", "Duduk"], ["Stand", "Berdiri"], ["Cook", "Memasak"],
      ["Play", "Bermain"], ["Help", "Menolong"], ["Throw", "Melempar"], ["Catch", "Menangkap"],
      ["Kick", "Menendang"], ["Wash", "Mencuci"]
    ],
    prepositions: [
      ["The cat is ____ the table", "under", "Kucing itu di bawah meja"],
      ["The book is ____ the bag", "in", "Buku itu di dalam tas"],
      ["The ball is ____ the box", "on", "Bola itu di atas kotak"],
      ["The chair is ____ the table", "near", "Kursi itu dekat meja"],
      ["The school is ____ the park", "beside", "Sekolah itu di samping taman"],
      ["The teacher is ____ the class", "in front of", "Guru itu di depan kelas"],
      ["The board is ____ the students", "behind", "Papan itu di belakang murid-murid"],
      ["The pencil is ____ the book", "next to", "Pensil itu di sebelah buku"],
      ["The bird flies ____ the house", "above", "Burung terbang di atas rumah"],
      ["The rabbit hides ____ the tree", "behind", "Kelinci bersembunyi di belakang pohon"],
      ["The shoes are ____ the bed", "under", "Sepatu ada di bawah tempat tidur"],
      ["The picture is ____ the wall", "on", "Gambar itu di dinding"],
      ["The dog sits ____ the door", "near", "Anjing duduk dekat pintu"],
      ["The cup is ____ the table", "on", "Cangkir ada di atas meja"],
      ["The children stand ____ the teacher", "in front of", "Anak-anak berdiri di depan guru"],
      ["The cat is ____ the box", "in", "Kucing di dalam kotak"],
      ["The lamp is ____ the desk", "on", "Lampu di atas meja"],
      ["The bag is ____ the chair", "under", "Tas di bawah kursi"],
      ["The car is ____ the house", "near", "Mobil dekat rumah"],
      ["The moon is ____ the clouds", "above", "Bulan di atas awan"],
      ["The garden is ____ the house", "behind", "Taman di belakang rumah"],
      ["The store is ____ the school", "beside", "Toko di samping sekolah"],
      ["The clock is ____ the door", "above", "Jam di atas pintu"],
      ["The apple is ____ the plate", "on", "Apel di atas piring"],
      ["The kitten sleeps ____ the sofa", "under", "Anak kucing tidur di bawah sofa"],
      ["The flowers are ____ the window", "near", "Bunga-bunga dekat jendela"],
      ["The boy stands ____ his father", "next to", "Anak itu berdiri di sebelah ayahnya"],
      ["The bus stops ____ the station", "in front of", "Bus berhenti di depan stasiun"],
      ["The fish swims ____ the water", "in", "Ikan berenang di dalam air"],
      ["The kite flies ____ the trees", "above", "Layang-layang terbang di atas pohon"]
    ],
    feelings: [
      ["Happy", "Senang"], ["Sad", "Sedih"], ["Angry", "Marah"], ["Scared", "Takut"],
      ["Tired", "Lelah"], ["Sleepy", "Mengantuk"], ["Hungry", "Lapar"], ["Thirsty", "Haus"],
      ["Excited", "Bersemangat"], ["Bored", "Bosan"], ["Surprised", "Terkejut"], ["Shy", "Malu"],
      ["Proud", "Bangga"], ["Worried", "Khawatir"], ["Calm", "Tenang"], ["Confused", "Bingung"],
      ["Brave", "Berani"], ["Lonely", "Kesepian"], ["Sick", "Sakit"], ["Comfortable", "Nyaman"],
      ["Nervous", "Gugup"], ["Jealous", "Cemburu"], ["Curious", "Penasaran"], ["Cheerful", "Ceria"],
      ["Grateful", "Bersyukur"], ["Relaxed", "Santai"], ["Disappointed", "Kecewa"], ["Joyful", "Gembira"],
      ["Upset", "Kesal"], ["Hopeful", "Penuh harap"]
    ],
    weatherWords: [
      ["Sunny", "Cerah"], ["Rainy", "Hujan"], ["Cloudy", "Berawan"], ["Windy", "Berangin"],
      ["Stormy", "Badai"], ["Snowy", "Bersalju"], ["Hot", "Panas"], ["Cold", "Dingin"],
      ["Warm", "Hangat"], ["Cool", "Sejuk"], ["Foggy", "Berkabut"], ["Thunder", "Guntur"],
      ["Lightning", "Kilat"], ["Rainbow", "Pelangi"], ["Drizzle", "Gerimis"], ["Weather", "Cuaca"],
      ["Season", "Musim"], ["Dry", "Kering"], ["Wet", "Basah"], ["Humid", "Lembap"],
      ["Freezing", "Membeku"], ["Icy", "Berlapis es"], ["Breeze", "Angin sepoi"], ["Frost", "Embun beku"],
      ["Hail", "Hujan es"], ["Cloud", "Awan"], ["Wind", "Angin"], ["Sun", "Matahari"],
      ["Mist", "Kabut tipis"], ["Overcast", "Mendung"]
    ],
    animals: [
      ["Cat", "Kucing"], ["Dog", "Anjing"], ["Fish", "Ikan"], ["Bird", "Burung"],
      ["Rabbit", "Kelinci"], ["Elephant", "Gajah"], ["Lion", "Singa"], ["Tiger", "Harimau"],
      ["Bear", "Beruang"], ["Monkey", "Monyet"], ["Horse", "Kuda"], ["Cow", "Sapi"],
      ["Goat", "Kambing"], ["Sheep", "Domba"], ["Chicken", "Ayam"], ["Duck", "Bebek"],
      ["Pig", "Babi"], ["Snake", "Ular"], ["Frog", "Katak"], ["Turtle", "Kura-kura"],
      ["Deer", "Rusa"], ["Fox", "Rubah"], ["Wolf", "Serigala"], ["Zebra", "Zebra"],
      ["Giraffe", "Jerapah"], ["Crocodile", "Buaya"], ["Butterfly", "Kupu-kupu"], ["Bee", "Lebah"],
      ["Ant", "Semut"], ["Mouse", "Tikus"]
    ],
    fruits: [
      ["Apple", "Apel"], ["Banana", "Pisang"], ["Orange", "Jeruk"], ["Mango", "Mangga"],
      ["Grape", "Anggur"], ["Watermelon", "Semangka"], ["Papaya", "Pepaya"], ["Pineapple", "Nanas"],
      ["Strawberry", "Stroberi"], ["Guava", "Jambu"], ["Melon", "Melon"], ["Durian", "Durian"],
      ["Rambutan", "Rambutan"], ["Coconut", "Kelapa"], ["Avocado", "Alpukat"], ["Lemon", "Lemon"],
      ["Cherry", "Ceri"], ["Pear", "Pir"], ["Peach", "Persik"], ["Kiwi", "Kiwi"],
      ["Lime", "Jeruk nipis"], ["Jackfruit", "Nangka"], ["Starfruit", "Belimbing"], ["Mangosteen", "Manggis"],
      ["Snakefruit", "Salak"], ["Dragonfruit", "Buah naga"], ["Longan", "Lengkeng"], ["Apricot", "Aprikot"],
      ["Fig", "Buah tin"], ["Plum", "Prem"]
    ],
    vegetables: [
      ["Carrot", "Wortel"], ["Potato", "Kentang"], ["Tomato", "Tomat"], ["Cabbage", "Kubis"],
      ["Spinach", "Bayam"], ["Onion", "Bawang"], ["Garlic", "Bawang putih"], ["Cucumber", "Timun"],
      ["Eggplant", "Terong"], ["Chili", "Cabai"], ["Corn", "Jagung"], ["Broccoli", "Brokoli"],
      ["Cauliflower", "Kembang kol"], ["Lettuce", "Selada"], ["Celery", "Seledri"], ["Pumpkin", "Labu"],
      ["Bean", "Kacang"], ["Pea", "Kacang polong"], ["Mushroom", "Jamur"], ["Radish", "Lobak"],
      ["Ginger", "Jahe"], ["Cassava", "Singkong"], ["Sweet potato", "Ubi"], ["Bean sprout", "Tauge"],
      ["Water spinach", "Kangkung"], ["Bitter melon", "Pare"], ["Long bean", "Kacang panjang"], ["Beetroot", "Bit"],
      ["Turnip", "Lobak putih"], ["Leek", "Daun bawang"]
    ],
    familyWords: [
      ["Family", "Keluarga"], ["Mother", "Ibu"], ["Father", "Ayah"], ["Parents", "Orang tua"],
      ["Sister", "Saudara perempuan"], ["Brother", "Saudara laki-laki"], ["Baby", "Bayi"], ["Child", "Anak"],
      ["Children", "Anak-anak"], ["Grandmother", "Nenek"], ["Grandfather", "Kakek"], ["Grandparents", "Kakek nenek"],
      ["Aunt", "Bibi"], ["Uncle", "Paman"], ["Cousin", "Sepupu"], ["Daughter", "Anak perempuan"],
      ["Son", "Anak laki-laki"], ["Sibling", "Saudara kandung"], ["Twin", "Kembar"], ["Wife", "Istri"],
      ["Husband", "Suami"], ["Grandma", "Nenek"], ["Grandpa", "Kakek"], ["Niece", "Keponakan perempuan"],
      ["Nephew", "Keponakan laki-laki"], ["Relatives", "Kerabat"], ["Home", "Rumah"], ["Older brother", "Kakak laki-laki"],
      ["Younger sister", "Adik perempuan"], ["Family tree", "Silsilah keluarga"]
    ],
    schoolWords: [
      ["School", "Sekolah"], ["Classroom", "Ruang kelas"], ["Teacher", "Guru"], ["Student", "Murid"],
      ["Principal", "Kepala sekolah"], ["Desk", "Meja belajar"], ["Chair", "Kursi"], ["Board", "Papan tulis"],
      ["Marker", "Spidol"], ["Eraser", "Penghapus"], ["Pencil", "Pensil"], ["Pen", "Pena"],
      ["Ruler", "Penggaris"], ["Notebook", "Buku catatan"], ["Backpack", "Tas sekolah"], ["Library", "Perpustakaan"],
      ["Canteen", "Kantin"], ["Playground", "Tempat bermain"], ["Homework", "Pekerjaan rumah"], ["Lesson", "Pelajaran"],
      ["Subject", "Mata pelajaran"], ["Math", "Matematika"], ["English", "Bahasa Inggris"], ["Science", "Sains"],
      ["Art", "Seni"], ["Music", "Musik"], ["Uniform", "Seragam"], ["Bell", "Bel"],
      ["Exam", "Ujian"], ["Classmate", "Teman sekelas"]
    ],
    clothesWords: [
      ["Shirt", "Kemeja"], ["T-shirt", "Kaos"], ["Pants", "Celana panjang"], ["Shorts", "Celana pendek"],
      ["Skirt", "Rok"], ["Dress", "Gaun"], ["Jacket", "Jaket"], ["Sweater", "Sweter"],
      ["Coat", "Mantel"], ["Hat", "Topi"], ["Cap", "Topi kasual"], ["Shoes", "Sepatu"],
      ["Socks", "Kaus kaki"], ["Sandals", "Sandal"], ["Boots", "Sepatu bot"], ["Scarf", "Syal"],
      ["Gloves", "Sarung tangan"], ["Belt", "Ikat pinggang"], ["Uniform", "Seragam"], ["Pajamas", "Piyama"],
      ["Raincoat", "Jas hujan"], ["Tie", "Dasi"], ["Pocket", "Saku"], ["Button", "Kancing"],
      ["Sleeve", "Lengan baju"], ["Collar", "Kerah"], ["Jeans", "Jins"], ["Hoodie", "Hudi"],
      ["Swimsuit", "Baju renang"], ["Slippers", "Sandal rumah"]
    ],
    transportWords: [
      ["Car", "Mobil"], ["Bus", "Bus"], ["Bicycle", "Sepeda"], ["Motorcycle", "Sepeda motor"],
      ["Train", "Kereta"], ["Airplane", "Pesawat"], ["Boat", "Perahu"], ["Ship", "Kapal"],
      ["Taxi", "Taksi"], ["Truck", "Truk"], ["Ambulance", "Ambulans"], ["Fire truck", "Mobil pemadam"],
      ["Police car", "Mobil polisi"], ["Helicopter", "Helikopter"], ["Scooter", "Skuter"], ["Subway", "Kereta bawah tanah"],
      ["Van", "Mobil van"], ["Jeep", "Jip"], ["Tram", "Trem"], ["Rocket", "Roket"],
      ["Road", "Jalan"], ["Bridge", "Jembatan"], ["Station", "Stasiun"], ["Airport", "Bandara"],
      ["Harbor", "Pelabuhan"], ["Ticket", "Tiket"], ["Driver", "Sopir"], ["Passenger", "Penumpang"],
      ["Traffic light", "Lampu lalu lintas"], ["Seat belt", "Sabuk pengaman"]
    ],
    placeWords: [
      ["House", "Rumah"], ["School", "Sekolah"], ["Market", "Pasar"], ["Hospital", "Rumah sakit"],
      ["Park", "Taman"], ["Library", "Perpustakaan"], ["Restaurant", "Restoran"], ["Shop", "Toko"],
      ["Bank", "Bank"], ["Post office", "Kantor pos"], ["Police station", "Kantor polisi"], ["Fire station", "Pemadam kebakaran"],
      ["Zoo", "Kebun binatang"], ["Museum", "Museum"], ["Beach", "Pantai"], ["Mountain", "Gunung"],
      ["River", "Sungai"], ["Garden", "Kebun"], ["Kitchen", "Dapur"], ["Bedroom", "Kamar tidur"],
      ["Bathroom", "Kamar mandi"], ["Living room", "Ruang tamu"], ["Classroom", "Ruang kelas"], ["Playground", "Tempat bermain"],
      ["Airport", "Bandara"], ["Station", "Stasiun"], ["Cinema", "Bioskop"], ["Bakery", "Toko roti"],
      ["Farm", "Peternakan"], ["Mosque", "Masjid"]
    ],
    foodWords: [
      ["Rice", "Nasi"], ["Noodles", "Mie"], ["Bread", "Roti"], ["Egg", "Telur"],
      ["Chicken", "Ayam"], ["Fish", "Ikan"], ["Meat", "Daging"], ["Soup", "Sup"],
      ["Cake", "Kue"], ["Cookie", "Kue kering"], ["Cheese", "Keju"], ["Butter", "Mentega"],
      ["Jam", "Selai"], ["Honey", "Madu"], ["Pizza", "Piza"], ["Burger", "Burger"],
      ["Sausage", "Sosis"], ["Sandwich", "Roti isi"], ["Salad", "Salad"], ["Fried rice", "Nasi goreng"],
      ["Porridge", "Bubur"], ["Meatball", "Bakso"], ["Satay", "Sate"], ["Tempeh", "Tempe"],
      ["Tofu", "Tahu"], ["Cereal", "Sereal"], ["Pancake", "Panekuk"], ["Ice cream", "Es krim"],
      ["Snack", "Camilan"], ["Lunch box", "Kotak bekal"]
    ],
    drinkWords: [
      ["Water", "Air"], ["Milk", "Susu"], ["Juice", "Jus"], ["Tea", "Teh"],
      ["Coffee", "Kopi"], ["Chocolate milk", "Susu cokelat"], ["Lemonade", "Limun"], ["Smoothie", "Smoothie"],
      ["Soda", "Soda"], ["Coconut water", "Air kelapa"], ["Mineral water", "Air mineral"], ["Orange juice", "Jus jeruk"],
      ["Apple juice", "Jus apel"], ["Mango juice", "Jus mangga"], ["Strawberry milk", "Susu stroberi"], ["Yogurt drink", "Minuman yogurt"],
      ["Hot chocolate", "Cokelat panas"], ["Herbal tea", "Teh herbal"], ["Iced tea", "Es teh"], ["Iced coffee", "Es kopi"],
      ["Soup drink", "Minuman sup"], ["Milkshake", "Milkshake"], ["Energy drink", "Minuman energi"], ["Ginger tea", "Teh jahe"],
      ["Honey water", "Air madu"], ["Green tea", "Teh hijau"], ["Black tea", "Teh hitam"], ["Soy milk", "Susu kedelai"],
      ["Fresh water", "Air segar"], ["Warm water", "Air hangat"]
    ],
    houseWords: [
      ["House", "Rumah"], ["Home", "Rumah"], ["Room", "Ruangan"], ["Door", "Pintu"],
      ["Window", "Jendela"], ["Wall", "Dinding"], ["Floor", "Lantai"], ["Roof", "Atap"],
      ["Kitchen", "Dapur"], ["Bedroom", "Kamar tidur"], ["Bathroom", "Kamar mandi"], ["Living room", "Ruang tamu"],
      ["Dining room", "Ruang makan"], ["Garage", "Garasi"], ["Garden", "Taman"], ["Yard", "Halaman"],
      ["Bed", "Tempat tidur"], ["Sofa", "Sofa"], ["Table", "Meja"], ["Chair", "Kursi"],
      ["Lamp", "Lampu"], ["Clock", "Jam"], ["Mirror", "Cermin"], ["Cupboard", "Lemari"],
      ["Shelf", "Rak"], ["Pillow", "Bantal"], ["Blanket", "Selimut"], ["Curtain", "Tirai"],
      ["Carpet", "Karpet"], ["Stairs", "Tangga"]
    ],
    jobsWords: [
      ["Teacher", "Guru"], ["Doctor", "Dokter"], ["Nurse", "Perawat"], ["Farmer", "Petani"],
      ["Police officer", "Polisi"], ["Firefighter", "Pemadam kebakaran"], ["Driver", "Sopir"], ["Pilot", "Pilot"],
      ["Chef", "Koki"], ["Baker", "Pembuat roti"], ["Dentist", "Dokter gigi"], ["Artist", "Seniman"],
      ["Singer", "Penyanyi"], ["Dancer", "Penari"], ["Writer", "Penulis"], ["Scientist", "Ilmuwan"],
      ["Engineer", "Insinyur"], ["Mechanic", "Montir"], ["Carpenter", "Tukang kayu"], ["Fisherman", "Nelayan"],
      ["Shopkeeper", "Penjaga toko"], ["Cashier", "Kasir"], ["Postman", "Tukang pos"], ["Soldier", "Tentara"],
      ["Actor", "Aktor"], ["Photographer", "Fotografer"], ["Librarian", "Pustakawan"], ["Gardener", "Tukang kebun"],
      ["Tailor", "Penjahit"], ["Barber", "Tukang cukur"]
    ],
    hobbyWords: [
      ["Reading", "Membaca"], ["Writing", "Menulis"], ["Drawing", "Menggambar"], ["Painting", "Melukis"],
      ["Singing", "Bernyanyi"], ["Dancing", "Menari"], ["Swimming", "Berenang"], ["Running", "Berlari"],
      ["Cycling", "Bersepeda"], ["Cooking", "Memasak"], ["Gardening", "Berkebun"], ["Fishing", "Memancing"],
      ["Camping", "Berkemah"], ["Hiking", "Mendaki"], ["Playing football", "Bermain sepak bola"], ["Playing badminton", "Bermain bulu tangkis"],
      ["Playing chess", "Bermain catur"], ["Playing music", "Bermain musik"], ["Watching movies", "Menonton film"], ["Taking photos", "Memotret"],
      ["Collecting stamps", "Mengoleksi perangko"], ["Collecting toys", "Mengoleksi mainan"], ["Flying a kite", "Bermain layang-layang"], ["Making crafts", "Membuat kerajinan"],
      ["Solving puzzles", "Memecahkan teka-teki"], ["Playing games", "Bermain game"], ["Skating", "Bermain sepatu roda"], ["Jumping rope", "Lompat tali"],
      ["Storytelling", "Bercerita"], ["Origami", "Origami"]
    ],
    timeWords: [
      ["Time", "Waktu"], ["Clock", "Jam"], ["Watch", "Jam tangan"], ["Hour", "Jam"],
      ["Minute", "Menit"], ["Second", "Detik"], ["Morning", "Pagi"], ["Afternoon", "Siang"],
      ["Evening", "Sore"], ["Night", "Malam"], ["Noon", "Tengah hari"], ["Midnight", "Tengah malam"],
      ["Today", "Hari ini"], ["Tomorrow", "Besok"], ["Yesterday", "Kemarin"], ["Early", "Awal"],
      ["Late", "Terlambat"], ["Now", "Sekarang"], ["Soon", "Segera"], ["Later", "Nanti"],
      ["Always", "Selalu"], ["Sometimes", "Kadang-kadang"], ["Never", "Tidak pernah"], ["Before", "Sebelum"],
      ["After", "Sesudah"], ["Fast", "Cepat"], ["Slow", "Lambat"], ["Schedule", "Jadwal"],
      ["Break time", "Waktu istirahat"], ["Bedtime", "Waktu tidur"]
    ],
    calendarWords: [
      ["Day", "Hari"], ["Week", "Minggu"], ["Month", "Bulan"], ["Year", "Tahun"],
      ["Monday", "Senin"], ["Tuesday", "Selasa"], ["Wednesday", "Rabu"], ["Thursday", "Kamis"],
      ["Friday", "Jumat"], ["Saturday", "Sabtu"], ["Sunday", "Minggu"], ["January", "Januari"],
      ["February", "Februari"], ["March", "Maret"], ["April", "April"], ["May", "Mei"],
      ["June", "Juni"], ["July", "Juli"], ["August", "Agustus"], ["September", "September"],
      ["October", "Oktober"], ["November", "November"], ["December", "Desember"], ["Birthday", "Ulang tahun"],
      ["Holiday", "Liburan"], ["Weekend", "Akhir pekan"], ["Season", "Musim"], ["Spring", "Musim semi"],
      ["Summer", "Musim panas"], ["Winter", "Musim dingin"]
    ],
    toyWords: [
      ["Toy", "Mainan"], ["Doll", "Boneka"], ["Teddy bear", "Boneka beruang"], ["Robot", "Robot"],
      ["Ball", "Bola"], ["Kite", "Layang-layang"], ["Puzzle", "Teka-teki"], ["Blocks", "Balok"],
      ["Car toy", "Mobil mainan"], ["Train set", "Kereta mainan"], ["Yo-yo", "Yoyo"], ["Marbles", "Kelereng"],
      ["Cards", "Kartu"], ["Board game", "Permainan papan"], ["Chess", "Catur"], ["Drum", "Drum"],
      ["Toy plane", "Pesawat mainan"], ["Toy boat", "Perahu mainan"], ["Skipping rope", "Tali lompat"], ["Balloon", "Balon"],
      ["Clay", "Tanah liat"], ["Crayons", "Krayon"], ["Sticker", "Stiker"], ["Mask", "Topeng"],
      ["Costume", "Kostum"], ["Swing", "Ayunan"], ["Slide", "Perosotan"], ["Sandbox", "Kotak pasir"],
      ["Spinning top", "Gasing"], ["Building set", "Set bangunan"]
    ],
    sportWords: [
      ["Sport", "Olahraga"], ["Football", "Sepak bola"], ["Basketball", "Bola basket"], ["Badminton", "Bulu tangkis"],
      ["Tennis", "Tenis"], ["Volleyball", "Bola voli"], ["Swimming", "Renang"], ["Running", "Lari"],
      ["Cycling", "Bersepeda"], ["Skating", "Sepatu roda"], ["Gymnastics", "Senam"], ["Karate", "Karate"],
      ["Boxing", "Tinju"], ["Baseball", "Bisbol"], ["Table tennis", "Tenis meja"], ["Golf", "Golf"],
      ["Hockey", "Hoki"], ["Archery", "Panahan"], ["Climbing", "Panjat"], ["Diving", "Menyelam"],
      ["Race", "Balapan"], ["Team", "Tim"], ["Player", "Pemain"], ["Coach", "Pelatih"],
      ["Goal", "Gol"], ["Score", "Skor"], ["Medal", "Medali"], ["Trophy", "Piala"],
      ["Winner", "Pemenang"], ["Practice", "Latihan"]
    ],
    natureWords: [
      ["Nature", "Alam"], ["Tree", "Pohon"], ["Flower", "Bunga"], ["Leaf", "Daun"],
      ["Grass", "Rumput"], ["Forest", "Hutan"], ["Mountain", "Gunung"], ["Hill", "Bukit"],
      ["River", "Sungai"], ["Lake", "Danau"], ["Sea", "Laut"], ["Beach", "Pantai"],
      ["Island", "Pulau"], ["Rock", "Batu"], ["Sand", "Pasir"], ["Soil", "Tanah"],
      ["Sky", "Langit"], ["Cloud", "Awan"], ["Sun", "Matahari"], ["Moon", "Bulan"],
      ["Star", "Bintang"], ["Rain", "Hujan"], ["Wind", "Angin"], ["Rainbow", "Pelangi"],
      ["Fire", "Api"], ["Waterfall", "Air terjun"], ["Cave", "Gua"], ["Desert", "Gurun"],
      ["Jungle", "Rimba"], ["Ocean", "Samudra"]
    ],
    questionWords: [
      ["____ is your name?", "What", "Siapa namamu?"],
      ["____ are you?", "How", "Bagaimana kabarmu?"],
      ["____ do you live?", "Where", "Di mana kamu tinggal?"],
      ["____ is your birthday?", "When", "Kapan ulang tahunmu?"],
      ["____ is your teacher?", "Who", "Siapa gurumu?"],
      ["____ do you like apples?", "Why", "Mengapa kamu suka apel?"],
      ["____ old are you?", "How", "Berapa umurmu?"],
      ["____ color is your bag?", "What", "Apa warna tasmu?"],
      ["____ book is this?", "Whose", "Buku siapa ini?"],
      ["____ one do you want?", "Which", "Yang mana yang kamu mau?"],
      ["____ many pencils do you have?", "How", "Berapa banyak pensil yang kamu punya?"],
      ["____ time is it?", "What", "Jam berapa sekarang?"],
      ["____ are you going?", "Where", "Ke mana kamu pergi?"],
      ["____ is she crying?", "Why", "Mengapa dia menangis?"],
      ["____ can help me?", "Who", "Siapa yang bisa membantuku?"],
      ["____ is your favorite food?", "What", "Apa makanan kesukaanmu?"],
      ["____ is my pencil?", "Where", "Di mana pensilku?"],
      ["____ does school start?", "When", "Kapan sekolah mulai?"],
      ["____ is that boy?", "Who", "Siapa anak laki-laki itu?"],
      ["____ are you sad?", "Why", "Mengapa kamu sedih?"],
      ["____ do you go to school?", "How", "Bagaimana kamu pergi ke sekolah?"],
      ["____ bag is this?", "Whose", "Tas siapa ini?"],
      ["____ shirt do you like?", "Which", "Baju yang mana yang kamu suka?"],
      ["____ is your mother?", "Where", "Di mana ibumu?"],
      ["____ day is it today?", "What", "Hari apa sekarang?"],
      ["____ are you happy?", "Why", "Mengapa kamu senang?"],
      ["____ is the party?", "When", "Kapan pestanya?"],
      ["____ is knocking the door?", "Who", "Siapa yang mengetuk pintu?"],
      ["____ tall is the tree?", "How", "Seberapa tinggi pohon itu?"],
      ["____ pen is yours?", "Which", "Pena yang mana milikmu?"]
    ],
    toBe: [
      ["I ____ happy", "am", "Aku senang"],
      ["You ____ kind", "are", "Kamu baik"],
      ["He ____ my brother", "is", "Dia saudara laki-lakiku"],
      ["She ____ my teacher", "is", "Dia guruku"],
      ["It ____ a red ball", "is", "Itu bola merah"],
      ["We ____ friends", "are", "Kami teman"],
      ["They ____ students", "are", "Mereka murid"],
      ["The cat ____ small", "is", "Kucing itu kecil"],
      ["The books ____ on the table", "are", "Buku-buku itu di atas meja"],
      ["My mother ____ in the kitchen", "is", "Ibuku di dapur"],
      ["My shoes ____ under the bed", "are", "Sepatuku di bawah tempat tidur"],
      ["I ____ ready", "am", "Aku siap"],
      ["The weather ____ cloudy", "is", "Cuacanya berawan"],
      ["The children ____ in the garden", "are", "Anak-anak di taman"],
      ["This pencil ____ blue", "is", "Pensil ini biru"],
      ["Those apples ____ sweet", "are", "Apel-apel itu manis"],
      ["My father ____ tall", "is", "Ayahku tinggi"],
      ["We ____ at school", "are", "Kami di sekolah"],
      ["The door ____ open", "is", "Pintunya terbuka"],
      ["The flowers ____ beautiful", "are", "Bunga-bunga itu indah"],
      ["I ____ seven years old", "am", "Aku berumur tujuh tahun"],
      ["The bus ____ yellow", "is", "Bus itu kuning"],
      ["You ____ my best friend", "are", "Kamu sahabatku"],
      ["The animals ____ hungry", "are", "Hewan-hewan itu lapar"],
      ["This story ____ interesting", "is", "Cerita ini menarik"],
      ["We ____ late", "are", "Kami terlambat"],
      ["She ____ very careful", "is", "Dia sangat hati-hati"],
      ["I ____ not afraid", "am", "Aku tidak takut"],
      ["The windows ____ clean", "are", "Jendela-jendela itu bersih"],
      ["It ____ time to study", "is", "Saatnya belajar"]
    ],
    pronouns: [
      ["____ am a student", "I", "Aku seorang murid"],
      ["____ are my friend", "You", "Kamu temanku"],
      ["____ is my father", "He", "Dia ayahku"],
      ["____ is my sister", "She", "Dia saudara perempuanku"],
      ["____ is a cat", "It", "Itu seekor kucing"],
      ["____ are playing football", "They", "Mereka bermain bola"],
      ["____ are in the classroom", "We", "Kami di ruang kelas"],
      ["Mother gives ____ a book", "me", "Ibu memberiku buku"],
      ["I can help ____", "you", "Aku bisa membantumu"],
      ["This bag belongs to ____", "him", "Tas ini miliknya"],
      ["The teacher calls ____", "her", "Guru memanggil dia"],
      ["Look at ____", "it", "Lihat itu"],
      ["Grandma visits ____", "us", "Nenek mengunjungi kami"],
      ["Please give the pencils to ____", "them", "Tolong berikan pensil kepada mereka"],
      ["____ likes apples", "He", "Dia suka apel"],
      ["____ likes oranges", "She", "Dia suka jeruk"],
      ["____ have two hands", "We", "Kami punya dua tangan"],
      ["____ have a new toy", "They", "Mereka punya mainan baru"],
      ["____ is raining today", "It", "Hari ini hujan"],
      ["____ am hungry", "I", "Aku lapar"],
      ["The dog follows ____", "me", "Anjing itu mengikutiku"],
      ["Dad is talking to ____", "us", "Ayah sedang berbicara kepada kami"],
      ["I see ____ at school", "them", "Aku melihat mereka di sekolah"],
      ["Can ____ open the door?", "you", "Bisakah kamu membuka pintu?"],
      ["____ is wearing a blue shirt", "He", "Dia memakai kemeja biru"],
      ["____ is drawing a flower", "She", "Dia menggambar bunga"],
      ["____ are good children", "They", "Mereka anak-anak baik"],
      ["____ are learning English", "We", "Kami sedang belajar Bahasa Inggris"],
      ["The bird is small. ____ can fly", "It", "Burung itu kecil. Ia bisa terbang"],
      ["This gift is for ____", "you", "Hadiah ini untukmu"]
    ],
    articles: [
      ["I have ____ apple", "an", "Aku punya sebuah apel"],
      ["She has ____ book", "a", "Dia punya sebuah buku"],
      ["He eats ____ egg", "an", "Dia makan sebuah telur"],
      ["This is ____ orange bag", "an", "Ini sebuah tas oranye"],
      ["I see ____ cat", "a", "Aku melihat seekor kucing"],
      ["____ sun is hot", "the", "Matahari panas"],
      ["We go to ____ school near our house", "the", "Kami pergi ke sekolah dekat rumah kami"],
      ["There is ____ umbrella", "an", "Ada sebuah payung"],
      ["My father drives ____ car", "a", "Ayahku mengemudikan sebuah mobil"],
      ["____ moon is bright", "the", "Bulan terang"],
      ["She wears ____ blue dress", "a", "Dia memakai sebuah gaun biru"],
      ["I want ____ ice cream", "an", "Aku ingin sebuah es krim"],
      ["This is ____ old chair", "an", "Ini sebuah kursi tua"],
      ["They found ____ toy", "a", "Mereka menemukan sebuah mainan"],
      ["____ teacher is kind", "the", "Guru itu baik"],
      ["He has ____ pencil", "a", "Dia punya sebuah pensil"],
      ["I saw ____ elephant", "an", "Aku melihat seekor gajah"],
      ["She is ____ honest girl", "an", "Dia anak perempuan yang jujur"],
      ["We read ____ story", "a", "Kami membaca sebuah cerita"],
      ["____ stars are beautiful tonight", "the", "Bintang-bintang indah malam ini"],
      ["There is ____ bird in the tree", "a", "Ada seekor burung di pohon"],
      ["I need ____ eraser", "an", "Aku butuh sebuah penghapus"],
      ["He bought ____ banana", "a", "Dia membeli sebuah pisang"],
      ["____ door is open", "the", "Pintunya terbuka"],
      ["She sees ____ ant", "an", "Dia melihat seekor semut"],
      ["I have ____ red balloon", "a", "Aku punya sebuah balon merah"],
      ["____ water in this glass is cold", "the", "Air di gelas ini dingin"],
      ["He wants ____ sandwich", "a", "Dia ingin sebuah sandwich"],
      ["This is ____ interesting game", "an", "Ini permainan yang menarik"],
      ["____ children are in the park", "the", "Anak-anak itu di taman"]
    ],
    possessives: [
      ["This is ____ book", "my", "Ini bukuku"],
      ["Is this ____ pencil?", "your", "Apakah ini pensilmu?"],
      ["He wears ____ shoes", "his", "Dia memakai sepatunya"],
      ["She loves ____ mother", "her", "Dia menyayangi ibunya"],
      ["The cat drinks ____ milk", "its", "Kucing itu minum susunya"],
      ["We clean ____ classroom", "our", "Kami membersihkan kelas kami"],
      ["They bring ____ bags", "their", "Mereka membawa tas mereka"],
      ["I wash ____ hands", "my", "Aku mencuci tanganku"],
      ["You should open ____ book", "your", "Kamu harus membuka bukumu"],
      ["Father drives ____ car", "his", "Ayah mengemudikan mobilnya"],
      ["Mother cooks in ____ kitchen", "her", "Ibu memasak di dapurnya"],
      ["The dog wags ____ tail", "its", "Anjing itu mengibaskan ekornya"],
      ["We love ____ family", "our", "Kami menyayangi keluarga kami"],
      ["The students finish ____ homework", "their", "Para murid menyelesaikan PR mereka"],
      ["This is ____ lunch box", "my", "Ini kotak makanku"],
      ["Where is ____ hat?", "your", "Di mana topimu?"],
      ["He reads ____ favorite story", "his", "Dia membaca cerita kesukaannya"],
      ["She packs ____ school bag", "her", "Dia menyiapkan tas sekolahnya"],
      ["The bird builds ____ nest", "its", "Burung itu membuat sarangnya"],
      ["We share ____ toys", "our", "Kami berbagi mainan kami"],
      ["They visit ____ grandma", "their", "Mereka mengunjungi nenek mereka"],
      ["I draw ____ house", "my", "Aku menggambar rumahku"],
      ["Please bring ____ ruler", "your", "Tolong bawa penggarismu"],
      ["He helps ____ little sister", "his", "Dia membantu adik perempuannya"],
      ["She feeds ____ rabbit", "her", "Dia memberi makan kelincinya"],
      ["The school opens ____ gate", "its", "Sekolah membuka gerbangnya"],
      ["We sing ____ song", "our", "Kami menyanyikan lagu kami"],
      ["The boys ride ____ bikes", "their", "Anak-anak laki-laki itu menaiki sepeda mereka"],
      ["I like ____ teacher", "my", "Aku menyukai guruku"],
      ["Do you know ____ address?", "their", "Apakah kamu tahu alamat mereka?"]
    ],
    simplePresent: [
      ["I ____ to school every day", "go", "Aku pergi ke sekolah setiap hari"],
      ["She ____ English", "studies", "Dia belajar Bahasa Inggris"],
      ["He ____ breakfast at seven", "eats", "Dia sarapan jam tujuh"],
      ["We ____ football after school", "play", "Kami bermain bola setelah sekolah"],
      ["They ____ books in the library", "read", "Mereka membaca buku di perpustakaan"],
      ["My mother ____ dinner", "cooks", "Ibuku memasak makan malam"],
      ["The dog ____ loudly", "barks", "Anjing itu menggonggong keras"],
      ["Birds ____ in the sky", "fly", "Burung-burung terbang di langit"],
      ["I ____ my teeth every morning", "brush", "Aku menyikat gigi setiap pagi"],
      ["He ____ his hands before eating", "washes", "Dia mencuci tangannya sebelum makan"],
      ["She ____ a red bag", "has", "Dia punya tas merah"],
      ["We ____ milk every morning", "drink", "Kami minum susu setiap pagi"],
      ["They ____ to music", "listen", "Mereka mendengarkan musik"],
      ["My father ____ a car", "drives", "Ayahku mengemudikan mobil"],
      ["The sun ____ in the east", "rises", "Matahari terbit di timur"],
      ["I ____ apples", "like", "Aku suka apel"],
      ["She ____ a beautiful song", "sings", "Dia menyanyikan lagu yang indah"],
      ["He ____ pictures of animals", "draws", "Dia menggambar hewan"],
      ["We ____ our teacher", "help", "Kami membantu guru kami"],
      ["The baby ____ when hungry", "cries", "Bayi itu menangis saat lapar"],
      ["You ____ very fast", "run", "Kamu berlari sangat cepat"],
      ["My sister ____ a bike", "rides", "Saudara perempuanku mengendarai sepeda"],
      ["The children ____ in the park", "play", "Anak-anak bermain di taman"],
      ["It ____ a lot in December", "rains", "Sering hujan di bulan Desember"],
      ["I ____ my homework after dinner", "do", "Aku mengerjakan PR setelah makan malam"],
      ["He ____ not like onions", "does", "Dia tidak suka bawang"],
      ["They ____ not go to school on Sunday", "do", "Mereka tidak pergi ke sekolah hari Minggu"],
      ["____ she like bananas?", "Does", "Apakah dia suka pisang?"],
      ["____ you have a pencil?", "Do", "Apakah kamu punya pensil?"],
      ["My brother ____ cartoons", "watches", "Saudara laki-lakiku menonton kartun"]
    ],
    colors: [
      ["Red", "#E5484D"], ["Blue", "#3B82F6"], ["Yellow", "#F5C518"], ["Green", "#5CB85C"],
      ["Black", "#2B2B2B"], ["White", "#FFFFFF"], ["Pink", "#F06BA8"], ["Purple", "#8B5CF6"],
      ["Orange", "#F5871F"], ["Brown", "#8B5A2B"], ["Gray", "#8A8F98"], ["Cyan", "#22D3EE"],
      ["Lime", "#84CC16"], ["Navy", "#1E3A8A"], ["Teal", "#0F766E"], ["Gold", "#D4AF37"],
      ["Silver", "#C0C0C0"], ["Maroon", "#7F1D1D"],
      ["Olive", "#708238"], ["Magenta", "#D946EF"], ["Violet", "#7C3AED"], ["Turquoise", "#40E0D0"],
      ["Coral", "#FF7F50"], ["Mint", "#98FB98"], ["Lavender", "#C4B5FD"], ["Indigo", "#4F46E5"],
      ["Peach", "#FFCBA4"], ["Rose", "#E11D48"], ["Sky Blue", "#87CEEB"], ["Dark Green", "#166534"]
    ],
    praise: ["Hebat!", "Keren!", "Great job!", "Well done!", "Pintar sekali!", "Super!", "Amazing!"]
  }
};
